[build]
target = "thumbv7em-none-eabihf"

# Owl 2
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "target-cpu=cortex-m4",
    "-C", "link-arg=-Towl2.ld",
]
runner = "./run.sh"

# Owl 3
#[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#rustflags = [
#    "-C", "link-arg=--nmagic",
#    "-C", "target-cpu=cortex-m7",
#    "-C", "link-arg=-Towl3.ld",
#]
#runner = "./run.sh"